name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: wetransform/docker-rasdaman
        token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
        ref: master
    - uses: actions/checkout@v2
      with:
        path: src
        fetch-depth: 0
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          wetransform/rasdaman
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.build
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
